name: Release
on:
  - workflow_dispatch
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.8.x

      - name: Install Dependencies
        run: npm ci
        
      - name: Compile Sass
        run: npm run sass:c

      - name: Format Code
        run: npm run format

      - name: Correct Code
        run: npm run test:fix

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🎨 | Cleaned Up Code"
          branch: master
