name: Mark Stale

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GIT_TOKEN }}
        days-before-stale: 25
        days-before-close: 5
        stale-issue-message: 'This issue is stale for 25+ days, so it will be closed in 5 more days'
        stale-pr-message: 'This issue is stale for 25+ days, so it will be closed in 5 more days'
        stale-issue-label: "Status: Stale"
        stale-pr-label: "Status: Stale"